server:
  port: 8080  # 网关端口

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true  # 开启服务发现
      routes:
        - id: service-consumer
          uri: lb://SERVICE-CONSUMER  # 注意服务名必须大写
          predicates:
            - Path=/consumer/**  # 匹配所有/consumer开头的路径
          filters:
            # 使用正则表达式重写路径，将/consumer/xxx 改为 /xxx
            - RewritePath=/consumer/(?<segment>.*), /$\{segment}
        - id: protected-route
          uri: lb://SERVICE-CONSUMER
          predicates:
            - Path=/protected/**
          filters:
            - name: CircuitBreaker
              args:
                name: gateway-circuit
                fallbackUri: forward:/fallback
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origin-patterns:
              - "*"   # 使用模式匹配，允许所有来源
            allowed-methods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowed-headers: "*"
            allow-credentials: true
            max-age: 3600




resilience4j:
  circuitbreaker:
    instances:
      gateway-circuit:
        failureRateThreshold: 40
        slowCallRateThreshold: 30
        slowCallDurationThreshold: 2s
        slidingWindowType: TIME_BASED
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka  # 注册中心地址

management:
  endpoints:
    web:
      exposure:
        include: "*"  # 暴露所有监控端点